### ISSUE TITLE
Install through ComfyUI Manager Menu did not work

### ISSUE THREAD

**Issue by Fredrum** [huchenlei/ComfyUI-layerdiffuse#19]
Hello and thanks for making this into a ComfyUI node!

I just tried to install using the ComfyUI Manager Menu -> Install Custom Nodes. I restarted as prompted.
But the new nodes are not available.

I'm on Windows 11
ComfyUI: 2021[36f7fa](2024-02-26)
Manager: V2.8.3

EDIT: I just update all of comfy but it didn't make any difference. Now,
ComfyUI: 2046[a38b9b](2024-03-04)
Manager: V2.9

Cheers! 
And thank you for your work!

**Comment by Fredrum** [comment]
I saw that you updated for cv2 and I just retried.
I think it's now working, at least I got the nodes!
(it is changing the output a lot though which I saw someone else mention. At least with the model I'm using.
but that's a completely different issue :) )

**Comment by huchenlei** [comment]
Yes, the layer-diffuse LoRA will modify the output even with fixed seed, and image quality might be affected. See also https://github.com/huchenlei/ComfyUI-layerdiffuse/issues/5
