### ISSUE TITLE
Execution of these two modules by the mac computer will cause the environment to crash，“Layer Diffusion Decode”和“Layer Diffusion Decode(BGBA)”

### ISSUE THREAD

**Issue by yiwangsimple** [huchenlei/ComfyUI-layerdiffuse#20]
The error message is as follows
“/AppleInternal/Library/BuildRoots/2acced82-df86-11ed-9b95-428477786501/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSNDArray/Kernels/MPSNDArraySort.mm:283: failed assertion `(null)" Axis = 4. This class only supports axis = 0, 1, 2, 3”

Please help me fix it, it's very important to me, thanks a lot!

**Comment by huchenlei** [comment]
Duplicated. Already tracked by https://github.com/huchenlei/ComfyUI-layerdiffuse/issues/1.
