### ISSUE TITLE
Any ideas on where to insert the encoder node when there are multiple KSamplers with different models? 

### ISSUE THREAD

**Issue by ynie** [huchenlei/ComfyUI-layerdiffuse#32]
Do I need to insert the encoder for both kSamplers? Just want to know if it's possible for my workflow atm. Thanks!

**Comment by ynie** [comment]
It doesn't seem like the model right now supports img2img. Just want to confirm. Thanks!

**Comment by huchenlei** [comment]
No. The model does not support img2img right now. Lvmin mentioned in https://github.com/layerdiffusion/sd-forge-layerdiffuse?tab=readme-ov-file#sd-forge-layerdiffuse that img2img will be release in about 1 week.
