### ISSUE TITLE
LayeredDiffusionApply: Error while deserializing header: MetadataIncompleteBuffer

### ISSUE THREAD

**Issue by Zlata-Salyukova** [huchenlei/ComfyUI-layerdiffuse#36]
Tried loading the first work flow just to generate the foreground with "Layered Diffusion Apply"
Using: Windows Portable latest install

Get this error when trying to run, no other similar issues found.

Note: I saw in issue #12 where they might have needed to download the Huggingface models, I don't think that is my issue.
I have not tried this, but let me know if that is it, downloading those isn't mentioned in the install instructions for this node-set.
https://github.com/huchenlei/ComfyUI-layerdiffuse/issues/12

Thx for any help!

<img width="974" alt="image" src="https://github.com/huchenlei/ComfyUI-layerdiffuse/assets/109472299/53ce3f84-f454-442a-8a15-26e7bccde4c0">

<img width="946" alt="image" src="https://github.com/huchenlei/ComfyUI-layerdiffuse/assets/109472299/732ca855-f20b-41be-a564-0acdb30cb07f">

![workflow](https://github.com/huchenlei/ComfyUI-layerdiffuse/assets/109472299/f90e4a73-135c-415a-a902-7b731fee8b3a)

**Comment by robji15** [comment]
so do I

**Comment by robji15** [comment]
issues/12  is the right way

**Comment by JozeeLin** [comment]
i have fixed this issue.
remove all models in ComfyUI_windows_portable\ComfyUI\models\layer_model, and download the models again.

**Comment by Zlata-Salyukova** [comment]
Solved by robj15 & JozeeLin
Issue #12 solves it by just re-downloading the model.
My only model in the folder was (layer_xl_transparent_conv.safetensors) to replace.

**Comment by Zlata-Salyukova** [comment]
Solved!
