### ISSUE TITLE
The images as inputs and dimensions only work with 1024x1024?

### ISSUE THREAD

**Issue by kevinabantostudio** [huchenlei/ComfyUI-layerdiffuse#39]
### What happened?

When I want to change to 512x512 or any multiple of 64, it doesn't work

### Steps to reproduce the problem

.

### What should have happened?

.

### Commit where the problem happens

ComfyUI:
ComfyUI-layerdiffuse:

### Sysinfo

.

### Console logs

```Shell
.
```

### Workflow json file

.

**Comment by huchenlei** [comment]
I think the 64 multiple is the issue with the decoding network design.
