### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 1 but got size 4 for tensor number 1 in the list.

### ISSUE THREAD

**Issue by kevinabantostudio** [huchenlei/ComfyUI-layerdiffuse#40]
### What happened?

When I want to generate 4 images with their 4 people without a background, an error appears and it only generates the people in the image, but it does not generate the people without a background.

### Steps to reproduce the problem

.

### What should have happened?

.

### Commit where the problem happens

ComfyUI:
ComfyUI-layerdiffuse:

### Sysinfo

.

### Console logs

```Shell
.
```

### Workflow json file

.

**Comment by huchenlei** [comment]
Explicit error message added in https://github.com/huchenlei/ComfyUI-layerdiffuse/commit/74aee185528d76e41486400145596314aac1b957
