### ISSUE TITLE
mac电脑执行这两个模块（“Layer Diffusion Decode”和“Layer Diffusion Decode(BGBA)” ）会导致Python崩溃

### ISSUE THREAD

**Issue by BannyLon** [huchenlei/ComfyUI-layerdiffuse#53]
我是💻 Mac M2，

运行ComfyUI一直很稳定，在运行ComfyUI-layerdiffuse执行到执行到LayerDiffusion解码(RGBA)，python就会自动中断运行，跳出错误提示，如下图：我尝试了很多种方法，都未能解决，求大佬！ 

![1710215419184](https://github.com/huchenlei/ComfyUI-layerdiffuse/assets/140726408/7c740305-299b-4446-a03c-4b015fd05f3f)
![Uploading 1710215419184.jpg…]()

**Comment by huchenlei** [comment]
Duplicated. Merged in to https://github.com/huchenlei/ComfyUI-layerdiffuse/issues/1.
