### ISSUE TITLE
[Feat]: what's the plan for Blended function which is now supported with SD1.5

### ISSUE THREAD

**Issue by vvip2u** [huchenlei/ComfyUI-layerdiffuse#56]
### What happened?

What about the plan for the implementation for the features below
- [Generate BG + Blended given FG](https://github.com/huchenlei/ComfyUI-layerdiffuse/blob/main/examples/layer_diffusion_cond_joint_fg.json)
- [Generate BG + FG + Blended together](https://github.com/huchenlei/ComfyUI-layerdiffuse/blob/main/examples/layer_diffusion_joint.json)
- [Generate FG + Blended given BG](https://github.com/huchenlei/ComfyUI-layerdiffuse/blob/main/examples/layer_diffusion_cond_joint_bg.json)

### Steps to reproduce the problem

None

### What should have happened?

None

### Commit where the problem happens

ComfyUI: None
ComfyUI-layerdiffuse: None

### Sysinfo

None

### Console logs

```Shell
None
```

### Workflow json file

None

**Comment by huchenlei** [comment]
These features are already implemented. See https://github.com/huchenlei/ComfyUI-layerdiffuse/issues/47.
