### ISSUE TITLE
[Bug]: Error occurred when executing LayeredDiffusionApply:

### ISSUE THREAD

**Issue by mbt1909432** [huchenlei/ComfyUI-layerdiffuse#64]
### What happened?

Error occurred when executing LayeredDiffusionApply:

File "F:\comfui\ComfyUI-aki-v1.3\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "F:\comfui\ComfyUI-aki-v1.3\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "F:\comfui\ComfyUI-aki-v1.3\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "F:\comfui\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-layerdiffuse\layered_diffusion.py", line 419, in apply_layered_diffusion
return ld_model.apply_layered_diffusion_attn_sharing(model)
File "F:\comfui\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-layerdiffuse\layered_diffusion.py", line 338, in apply_layered_diffusion_attn_sharing
model_path = load_file_from_url(
File "F:\comfui\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-layerdiffuse\lib_layerdiffusion\utils.py", line 114, in load_file_from_url
download_url_to_file(url, cached_file, progress=progress)
File "", line 28, in download_url_to_file_wrapper_inner
File "F:\comfui\ComfyUI-aki-v1.3\python\lib\site-packages\torch\hub.py", line 620, in download_url_to_file
u = urlopen(req)
File "F:\comfui\ComfyUI-aki-v1.3\python\lib\urllib\request.py", line 216, in urlopen
return opener.open(url, data, timeout)
File "F:\comfui\ComfyUI-aki-v1.3\python\lib\urllib\request.py", line 519, in open
response = self._open(req, data)
File "F:\comfui\ComfyUI-aki-v1.3\python\lib\urllib\request.py", line 536, in _open
result = self._call_chain(self.handle_open, protocol, protocol +
File "F:\comfui\ComfyUI-aki-v1.3\python\lib\urllib\request.py", line 496, in _call_chain
result = func(*args)
File "F:\comfui\ComfyUI-aki-v1.3\python\lib\urllib\request.py", line 1391, in https_open
return self.do_open(http.client.HTTPSConnection, req,
File "F:\comfui\ComfyUI-aki-v1.3\python\lib\urllib\request.py", line 1351, in do_open
raise URLError(err

### Steps to reproduce the problem

a

### What should have happened?

a

### Commit where the problem happens

ComfyUI:
ComfyUI-layerdiffuse:

### Sysinfo

NVIDIA GeForce RTX 4070 Ti

### Console logs

```Shell
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\comfui\ComfyUI-aki-v1.3\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\comfui\ComfyUI-aki-v1.3\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\comfui\ComfyUI-aki-v1.3\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\comfui\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-layerdiffuse\layered_diffusion.py", line 419, in apply_layered_diffusion
    return ld_model.apply_layered_diffusion_attn_sharing(model)
  File "F:\comfui\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-layerdiffuse\layered_diffusion.py", line 338, in apply_layered_diffusion_attn_sharing
    model_path = load_file_from_url(
  File "F:\comfui\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-layerdiffuse\lib_layerdiffusion\utils.py", line 114, in load_file_from_url
    download_url_to_file(url, cached_file, progress=progress)
  File "<enhanced_experience patches.hfmirror.torchhub>", line 28, in download_url_to_file_wrapper_inner
  File "F:\comfui\ComfyUI-aki-v1.3\python\lib\site-packages\torch\hub.py", line 620, in download_url_to_file
    u = urlopen(req)
  File "F:\comfui\ComfyUI-aki-v1.3\python\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "F:\comfui\ComfyUI-aki-v1.3\python\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "F:\comfui\ComfyUI-aki-v1.3\python\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "F:\comfui\ComfyUI-aki-v1.3\python\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "F:\comfui\ComfyUI-aki-v1.3\python\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "F:\comfui\ComfyUI-aki-v1.3\python\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>
```

### Workflow json file

{
  "last_node_id": 36,
  "last_link_id": 51,
  "nodes": [
    {
      "id": 14,
      "type": "VAEDecode",
      "pos": [
        1275,
        198
      ],
      "size": {
        "0": 210,
        "1": 46
      },
      "flags": {},
      "order": 6,
      "mode": 0,
      "inputs": [
        {
          "name": "samples",
          "type": "LATENT",
          "link": 21,
          "label": "samples"
        },
        {
          "name": "vae",
          "type": "VAE",
          "link": 22,
          "slot_index": 1,
          "label": "vae"
        }
      ],
      "outputs": [
        {
          "name": "IMAGE",
          "type": "IMAGE",
          "links": [
            29,
            50
          ],
          "shape": 3,
          "slot_index": 0,
          "label": "IMAGE"
        }
      ],
      "properties": {
        "Node name for S&R": "VAEDecode"
      }
    },
    {
      "id": 3,
      "type": "KSampler",
      "pos": [
        911,
        198
      ],
      "size": {
        "0": 315,
        "1": 262
      },
      "flags": {},
      "order": 5,
      "mode": 0,
      "inputs": [
        {
          "name": "model",
          "type": "MODEL",
          "link": 19,
          "label": "model"
        },
        {
          "name": "positive",
          "type": "CONDITIONING",
          "link": 4,
          "label": "positive"
        },
        {
          "name": "negative",
          "type": "CONDITIONING",
          "link": 6,
          "label": "negative"
        },
        {
          "name": "latent_image",
          "type": "LATENT",
          "link": 2,
          "label": "latent_image"
        }
      ],
      "outputs": [
        {
          "name": "LATENT",
          "type": "LATENT",
          "links": [
            21,
            49
          ],
          "slot_index": 0,
          "label": "LATENT"
        }
      ],
      "properties": {
        "Node name for S&R": "KSampler"
      },
      "widgets_values": [
        912707468882145,
        "randomize",
        20,
        8,
        "euler",
        "normal",
        1
      ]
    },
    {
      "id": 13,
      "type": "LayeredDiffusionApply",
      "pos": [
        468,
        -2
      ],
      "size": {
        "0": 327.8314208984375,
        "1": 106.42147827148438
      },
      "flags": {},
      "order": 2,
      "mode": 0,
      "inputs": [
        {
          "name": "model",
          "type": "MODEL",
          "link": 18,
          "label": "model"
        }
      ],
      "outputs": [
        {
          "name": "MODEL",
          "type": "MODEL",
          "links": [
            19
          ],
          "shape": 3,
          "slot_index": 0,
          "label": "MODEL"
        }
      ],
      "properties": {
        "Node name for S&R": "LayeredDiffusionApply"
      },
      "widgets_values": [
        "SD15, Attention Injection, attn_sharing",
        1
      ]
    },
    {
      "id": 20,
      "type": "PreviewImage",
      "pos": [
        1542,
        450
      ],
      "size": {
        "0": 289.6058349609375,
        "1": 299.6588134765625
      },
      "flags": {},
      "order": 7,
      "mode": 0,
      "inputs": [
        {
          "name": "images",
          "type": "IMAGE",
          "link": 29,
          "label": "images"
        }
      ],
      "properties": {
        "Node name for S&R": "PreviewImage"
      }
    },
    {
      "id": 5,
      "type": "EmptyLatentImage",
      "pos": [
        480,
        691
      ],
      "size": {
        "0": 315,
        "1": 106
      },
      "flags": {},
      "order": 0,
      "mode": 0,
      "outputs": [
        {
          "name": "LATENT",
          "type": "LATENT",
          "links": [
            2
          ],
          "slot_index": 0,
          "label": "LATENT"
        }
      ],
      "properties": {
        "Node name for S&R": "EmptyLatentImage"
      },
      "widgets_values": [
        512,
        512,
        1
      ]
    },
    {
      "id": 36,
      "type": "LayeredDiffusionDecodeRGBA",
      "pos": [
        1629,
        111
      ],
      "size": {
        "0": 243.60000610351562,
        "1": 102
      },
      "flags": {},
      "order": 8,
      "mode": 0,
      "inputs": [
        {
          "name": "samples",
          "type": "LATENT",
          "link": 49,
          "label": "samples"
        },
        {
          "name": "images",
          "type": "IMAGE",
          "link": 50,
          "label": "images"
        }
      ],
      "outputs": [
        {
          "name": "IMAGE",
          "type": "IMAGE",
          "links": [
            51
          ],
          "shape": 3,
          "label": "IMAGE"
        }
      ],
      "properties": {
        "Node name for S&R": "LayeredDiffusionDecodeRGBA"
      },
      "widgets_values": [
        "SD15",
        16
      ]
    },
    {
      "id": 4,
      "type": "CheckpointLoaderSimple",
      "pos": [
        -230,
        238
      ],
      "size": {
        "0": 315,
        "1": 98
      },
      "flags": {},
      "order": 1,
      "mode": 0,
      "outputs": [
        {
          "name": "MODEL",
          "type": "MODEL",
          "links": [
            18
          ],
          "slot_index": 0,
          "label": "MODEL"
        },
        {
          "name": "CLIP",
          "type": "CLIP",
          "links": [
            3,
            5
          ],
          "slot_index": 1,
          "label": "CLIP"
        },
        {
          "name": "VAE",
          "type": "VAE",
          "links": [
            22
          ],
          "slot_index": 2,
          "label": "VAE"
        }
      ],
      "properties": {
        "Node name for S&R": "CheckpointLoaderSimple"
      },
      "widgets_values": [
        "helloobjects_V15evae.safetensors"
      ]
    },
    {
      "id": 27,
      "type": "PreviewImage",
      "pos": [
        1970,
        202
      ],
      "size": {
        "0": 289.6058349609375,
        "1": 299.6588134765625
      },
      "flags": {},
      "order": 9,
      "mode": 0,
      "inputs": [
        {
          "name": "images",
          "type": "IMAGE",
          "link": 51,
          "slot_index": 0,
          "label": "images"
        }
      ],
      "properties": {
        "Node name for S&R": "PreviewImage"
      }
    },
    {
      "id": 7,
      "type": "CLIPTextEncode",
      "pos": [
        413,
        389
      ],
      "size": {
        "0": 425.27801513671875,
        "1": 180.6060791015625
      },
      "flags": {},
      "order": 4,
      "mode": 0,
      "inputs": [
        {
          "name": "clip",
          "type": "CLIP",
          "link": 5,
          "label": "clip"
        }
      ],
      "outputs": [
        {
          "name": "CONDITIONING",
          "type": "CONDITIONING",
          "links": [
            6
          ],
          "slot_index": 0,
          "label": "CONDITIONING"
        }
      ],
      "properties": {
        "Node name for S&R": "CLIPTextEncode"
      },
      "widgets_values": [
        "text, watermark"
      ]
    },
    {
      "id": 6,
      "type": "CLIPTextEncode",
      "pos": [
        396,
        174
      ],
      "size": {
        "0": 422.84503173828125,
        "1": 164.31304931640625
      },
      "flags": {},
      "order": 3,
      "mode": 0,
      "inputs": [
        {
          "name": "clip",
          "type": "CLIP",
          "link": 3,
          "label": "clip"
        }
      ],
      "outputs": [
        {
          "name": "CONDITIONING",
          "type": "CONDITIONING",
          "links": [
            4
          ],
          "slot_index": 0,
          "label": "CONDITIONING"
        }
      ],
      "properties": {
        "Node name for S&R": "CLIPTextEncode"
      },
      "widgets_values": [
        "beautiful scenery nature glass bottle landscape, , purple galaxy bottle,"
      ]
    }
  ],
  "links": [
    [
      2,
      5,
      0,
      3,
      3,
      "LATENT"
    ],
    [
      3,
      4,
      1,
      6,
      0,
      "CLIP"
    ],
    [
      4,
      6,
      0,
      3,
      1,
      "CONDITIONING"
    ],
    [
      5,
      4,
      1,
      7,
      0,
      "CLIP"
    ],
    [
      6,
      7,
      0,
      3,
      2,
      "CONDITIONING"
    ],
    [
      18,
      4,
      0,
      13,
      0,
      "MODEL"
    ],
    [
      19,
      13,
      0,
      3,
      0,
      "MODEL"
    ],
    [
      21,
      3,
      0,
      14,
      0,
      "LATENT"
    ],
    [
      22,
      4,
      2,
      14,
      1,
      "VAE"
    ],
    [
      29,
      14,
      0,
      20,
      0,
      "IMAGE"
    ],
    [
      49,
      3,
      0,
      36,
      0,
      "LATENT"
    ],
    [
      50,
      14,
      0,
      36,
      1,
      "IMAGE"
    ],
    [
      51,
      36,
      0,
      27,
      0,
      "IMAGE"
    ]
  ],
  "groups": [],
  "config": {},
  "extra": {},
  "version": 0.4
}

**Comment by huchenlei** [comment]
I think this is because of GFW blocking your connection to huggingface. If you are in mainland China, you can try download models from alternative sources, and put them under `models/layer_model`.

**Comment by mbt1909432** [comment]
thank you sir



发自我的iPhone


------------------ Original ------------------
From: Chenlei Hu ***@***.***&gt;
Date: Sat,Mar 30,2024 11:38 AM
To: huchenlei/ComfyUI-layerdiffuse ***@***.***&gt;
Cc: Xu Yilong ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [huchenlei/ComfyUI-layerdiffuse] [Bug]: Error occurred whenexecuting LayeredDiffusionApply: (Issue #64)





 
I think this is because of GFW blocking your connection to huggingface. If you are in mainland China, you can try download models from alternative sources, and put them under models/layer_model.
