### ISSUE TITLE
No SD15 item in selections

### ISSUE THREAD

**Issue by jkla139** [huchenlei/ComfyUI-layerdiffuse#65]
![image](https://github.com/huchenlei/ComfyUI-layerdiffuse/assets/44624598/f32b7159-fe66-4d68-b7cf-efaa6c20a7d2)

**Comment by huchenlei** [comment]
You need to use `Layer Diffuse Cond Joint Apply` node instead. The joint node only supports SD15 and produces conditioned FG/BG + blended image in single pass.
