### ISSUE TITLE
diffusers==0.25.0  Does this dependency require this version? Can it be higher?

### ISSUE THREAD

**Issue by tanglup** [huchenlei/ComfyUI-layerdiffuse#9]

**Comment by huchenlei** [comment]
Yes, it is mandatory. diffusers 0.25.0 is the version used in SD Forge. See https://github.com/lllyasviel/stable-diffusion-webui-forge/blob/main/requirements_versions.txt.

You can file an issue in SD Forge repo to let lvmin do the upgrade, but we will keep the version synced with SD Forge here.

**Comment by tanglup** [comment]
> 是的，这是强制性的。differs 0.25.0 是 SD Forge 中使用的版本。请参阅https://github.com/lllyasviel/stable-diffusion-webui-forge/blob/main/requirements_versions.txt。
> 
> 您可以在 SD Forge 存储库中提交问题，让 lvmin 进行升级，但我们将在此处保持与 SD Forge 的版本同步。
> 
> 如果您的扩散器版本与其他扩展冲突，我建议您设置单独的 python venvs。

Okay, I understand

**Comment by toyxyz** [comment]
Works with diffusers 0.26.3. 
![image](https://github.com/huchenlei/ComfyUI-layerdiffuse/assets/8006000/01bfbcf4-d2b7-4861-a563-f08b36df8333)

**Comment by huchenlei** [comment]
Diffusers version requirement relaxed to >= 0.25.0
